# Generated by Django 5.1.7 on 2025-03-31 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_caetgoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caetgoria',
            new_name='Categoria',
        ),
    ]
